### PR TITLE
Added support for the Z64 and B64 compression schemes.

### PR DESCRIPTION
**Pull request by danzk**
Hello, 
I am making a pull request to add support for the Z64 and B64 compression schemes.

- I added Z64 and B64 helper classes. 
- I changed ImageResult to hold raw byte data to reduce the amount of conversions between byte[] and string. 
- I optimized ACS compression scheme to remove "G" character usage. "G" encodes for a repeat of 1, so you end using 2 characters instead of just 1.  
- I updated Tests to cover all compression schemes. I had to make some changes to existing tests to cover the optimized ACS. 
- I updated TestConsole to cover all compression schemes, all the new compression schemes can be displayed by Labelary site. 
- I updated Viewer to cover all compression schemes, more elements generated by ZebraDesigner can be displayed.

### CODE REVIEW

**Comment by danzk** [comment]
It seems like the native compression library on linux is using a different compression level compared to windows. 
I checked on lab
I will download WSL2 and debug on there, i also noticed that i used the wrong header for compression level.

**Comment by tinohager** [comment]
I can not check the pull request at the moment am unfortunately full with work, sorry

**Review by primo-ppcg — CHANGES_REQUESTED** [review]
In general, the additions seem well-written.

Regarding the difference in compression levels, I also find it somewhat surprising that different platforms have different defaults. The compression level should probably be supplied explicitly for the sake of cross-platform consistency. The `Deflate` methods of the Z64 helpers contain a `level` parameter in their docstrings, is this intended to be added? These helpers also contain a commented out `Uncompress(byte[] bytes)` method. Is this left to do, or unnecessary?

Minor style nitpicks:
- I personally prefer to initialize `static readonly` members directly, rather than in a static constructor. I believe this is also how it has done throughout the code base.
- Newline usage is somewhat inconsistent. In places, there are multiple newlines after a closing brace, and in other places none. In general:
  - After opening brace, prefer no newline.
  - After closing brace, prefer one newline, unless it is immediately followed by another brace, in which case the newline may be omitted.
  - After members, prefer one newline, unless there are similar members each on one line, in which case the newline between them maybe be omitted.

The `Crc16` implementation is a bit verbose. It can also be computed 4 bits at a time, which is somewhat less ominous to look at:

```csharp
namespace BinaryKits.Label.Helpers
{
    /// <summary>
    /// Calculate Crc16 Checksum.
    /// </summary>
    internal class Crc16
    {
        private static ushort[] crc16_table = {
           0x0000, 0x1021, 0x2042, 0x3063,
           0x4084, 0x50A5, 0x60C6, 0x70E7,
           0x8108, 0x9129, 0xA14A, 0xB16B,
           0xC18C, 0xD1AD, 0xE1CE, 0xF1EF
        };

        public static ushort Compute(byte[] bytes)
        {
            int crc = 0;
            foreach (byte b in bytes)
            {
                crc ^= (b << 8);
                crc = (crc << 4) ^ crc16_table[(crc >> 12) & 0xF];
                crc = (crc << 4) ^ crc16_table[(crc >> 12) & 0xF];
            }

            return (ushort)(crc & 0xFFFF);
        }

        public static string ComputeHex(byte[] bytes)
        {
            return Compute(bytes).ToString("x4");
        }

    }
}
```
Prefer `bytes[]` rather than a `string` parameter. The current implementation would compute the checksum on UTF-16 codepoints/surrogates, which is not strictly speaking correct. I'm also fairly certain you meant `"x4"` rather than `"X2"` in the hex conversion.

**Comment by danzk** [comment]
> primo-ppcg

Thanks for the feedback, your Crc16 implementation is much cleaner. 
My initial implementation was based on https://github.com/metafloor/zpl-image which is functional but not pretty. 
Based on some testing it seems like Linux is defaulting to CompressionLevel.SmallestSize instead of Optimal like windows. 
I made an ifdef to just use ZLibStream on .NET core and explicitly set CompressionLevel.Optimal. 
It also seems that you will get different results when using .NET Framework 4.8.
However, I was able to print all levels of compression on a physical printer so I don't think it is a huge issue.

**Comment by danzk** [comment]
> On Linux and macOS where zlib is available everywhere, we use the one installed on the OS. On Windows where it's not, we have to distribute it with .NET Core, in the clrcompression.dll, and since we're distributing it anyway, we then use Intel's optimized version of zlib.
https://github.com/dotnet/runtime/issues/30539#issuecomment-519735047

Do you think I should just switch to SharpZipLib instead?

**Comment by primo-ppcg** [comment]
> Do you think I should just switch to SharpZipLib instead?

I don't think the .NET team has made a mistake here. In general, is better to prefer less dependencies. If the compression level can't be easily unified across platforms, having a different test for different platforms would also be acceptable.

The primary purpose of the test suite is to prevent accidental regressions.

**Comment by primo-ppcg** [comment]
I think the compression have been unified across all platforms, now.

However, I still see an error in ACS compression on .NET 4.7.2:

```csharp
Compress_ValidData3_Successful
   Source: ZebraACSCompressionHelperTest.cs line 102
   Duration: < 1 ms

  Message: 
Assert.AreEqual failed. Expected:<gF8I0JFJ0JFI0!::JFJ0JFJ0JF::gF>. Actual:<gF8I0JFJ0JFI0!8I0JFJ0JFI0!8I0JFJ0JFI0!JFJ0JFJ0JFJFJ0JFJ0JFJFJ0JFJ0JFgF>. 

  Stack Trace: 
ZebraACSCompressionHelperTest.Compress_ValidData3_Successful() line 105
```

Perhaps you could check that?

**Pull request merged**
