### PR TITLE
Drop BarcodeLib dependency

### LINKED ISSUE #145: ElementDrawer for barcodes with interpretation line throwing on OSX-Arm64/.NET 7.0
Environment: OSX (Ventura) on Apple Silicon with .NET 7.0

I've worked on a REST wrapper around some ZPL/Label Printing functionality and I've noticed that using the Viewer library to generate barcodes that contain an interpretation line does not work on my dev machine even if making `libgdiplus` available (with that is running fine with the current /dotnet/sdk:7.0 docker image though, so it's not really a blocker for the project).

```csharp
var labelFont = new SKFont(labelTypeFace, labelFontSize).ToSystemDrawingFont();
int labelHeight = barcode.PrintInterpretationLine ? labelFont.Height : 0;
```
https://github.com/BinaryKits/BinaryKits.Zpl/blob/93caafc2c7a8eb58eb13bb0ce55f7dfe84d27499/src/BinaryKits.Zpl.Viewer/ElementDrawers/Barcode128ElementDrawer.cs#L100

The `labelFont.Height` property is throwing in these cases. I also tried replacing the font loader with a custom one but it didn't change the outcome. Since MS is not pursuing cross-platform support for `System.Common.Drawing` I guess it would require dropping the dependency on that to support this scenario. I guess this might not be worth the effort given that the viewer is fine running in Docker but I just wanted to let you know (thanks for the whole library, was a huge time-saver).

### LINKED ISSUE #154: System.AccessViolationException: 'Attempted to read or write protected memory. This is often an indication that other memory is corrupt.'
image
Getting System.AccessViolationException in Drawer.draw

### LINKED ISSUE #170: System.AccessViolationException: Attempted to read or write protected memory
BinaryKits Exception

> Exception==>System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at System.Drawing.SafeNativeMethods.Gdip.GdipGetFontHeight(HandleRef font, HandleRef graphics, Single& size)
   at System.Drawing.Font.GetHeight(Graphics graphics)
   at System.Drawing.Font.GetHeight()
   at System.Drawing.Font.get_Height()
   at BarcodeLib.Barcode.Generate_Image()
   at BarcodeLib.Barcode.Encode()
   at BinaryKits.Zpl.Viewer.ElementDrawers.Barcode128ElementDrawer.Draw(ZplElementBase element, DrawerOptions options)
   at BinaryKits.Zpl.Viewer.ZplElementDrawer.Draw(ZplElementBase[] elements, Double labelWidth, Double labelHeight, Int32 printDensityDpmm)
   at PreviewGenerator.Preview.LabelPreviewFactory.VirualPrinterPreview(String labelZpl, Double scaleFactor) 

this is the code we use
BinaryKits code

we are sometimes getting this Exception , and it leads to the application crashing. 
all exceptions are happening at Barcode128ElementDrawer.
I am using the analyzer.Analyze two times [the exception is not happening every time even with the same ZPL] it is happening arbitrarily  , the first one to download the graphics which will be called on the label, the second time is for processing the label.
I tried to combine the graphics download with label but it was sometimes also raising the same exception.

also please note we are downloading 29 images using the download graphics, these images it will stay in the virtual printer storage, and each label will contain at maximum 3 images only.

I noticed that there were a similar issue raised before with exception similar to this one but it is closed and still the issue is present.
this is the previously raised issue #154
your support is much appreciated.

### PR DESCRIPTION
**Pull request by primo-ppcg**
Drops the BarcodeLib dependency.

Fixes #145
Fixes #154
Fixes #170

Additionally:
- Code39 and I2of5 now support variable WideToNarrow ratio.
- EAN13 interpretation lines now respect chosen font face.
- EAN13 are no longer drawn with a white background.

This PR will likely remain in draft status until the next release of ZXing.NET, as I am waiting on the resolution of a few issues:
https://github.com/micjahn/ZXing.Net/pull/503
https://github.com/micjahn/ZXing.Net/pull/504

### CODE REVIEW

**Comment by YipingRuan** [comment]
@primo-ppcg 
Should this PR remain "work in progress"?

**Comment by primo-ppcg** [comment]
> @primo-ppcg Should this PR remain "work in progress"?

Unfortunately, Code128 barcodes containing a space will cause an error with the current version of ZXing.Net (https://github.com/micjahn/ZXing.Net/pull/504). This is due to a bug in the parent project that's also been corrected (https://github.com/zxing/zxing/pull/1658). This PR unfortunately cannot be merged until the next version of ZXing.Net is released.

**Comment by ivanjx** [comment]
any progress? all the external issues mentioned are fixed.

**Comment by primo-ppcg** [comment]
It's becoming a long wait for the next release of ZXing.NET. I'm going to get some of the open PRs merged and rework this for all barcodes except Code 128.

**Comment by YipingRuan** [comment]
@primo-ppcg 
Thank you, will you also include the `SixLabors.ImageSharp` fixes, like https://github.com/BinaryKits/BinaryKits.Zpl/pull/223 ?

**Comment by primo-ppcg** [comment]
> @primo-ppcg Thank you, will you also include the `SixLabors.ImageSharp` fixes, like #223 ?

For sure, as per the [github advisory](https://github.com/advisories/GHSA-65x7-c272-7g7r).

**Pull request closed without merging**
