### PR TITLE
Optimize Viewer

### PR DESCRIPTION
**Pull request by tinohager**
- Add new test data
- Optimize web interface
- Add new ZplCommandAnalyzers

### CODE REVIEW

**Comment by YipingRuan** [comment]
Somehow the barcode is not correct on my local.
Is this known and okay to merge current progress?

image

**Comment by tinohager** [comment]
Yes work in progress :)

**Comment by tinohager** [comment]
@YipingRuan i have add ZplFieldTypeset and change the FieldOrigin logic. I need this for the Viewer. Please check this commit.

**Comment by tinohager** [comment]
@YipingRuan can you check again the barcode, i have try to optimize the calculation logic and switch to an other package (only on code128 at the moment)

**Comment by YipingRuan** [comment]
Not working...
image

**Comment by YipingRuan** [comment]
Btw, on Linux the viewer got some problem, let me think.

System.TypeInitializationException: The type initializer for 'SkiaSharp.SKImageInfo' threw an exception.
 ---> System.DllNotFoundException: Unable to load shared library 'libSkiaSharp' or one of its dependencies.

**Comment by tinohager** [comment]
> Not working...
> image

what is inside the `0:` object

**Comment by tinohager** [comment]
An example preview from windows

image

**Comment by YipingRuan** [comment]
My bad, it works after I relaunch. 
(And seems no need to click Render button, the preview updates when you switch).

**Comment by tinohager** [comment]
@YipingRuan What do you think of the current status?

**Comment by YipingRuan** [comment]
My only doubts is why our label size is bigger than labelary?

**Comment by tinohager** [comment]
We do not have a label size yet. Ultimately, this only defines the image width and height. Labelary has a configuration for this where you can set the label size.

**Comment by tinohager** [comment]
@YipingRuan

Open issues/questions

- bottomToTop we have a better naming here?
- add reversePrint for all drawing elements? (exclude ZplDownloadGraphics, ZplRaw, ...)
- Code128BarcodeFieldData add mode logic
- I have change the position system is this okay?

Some other open points of the viewer
https://github.com/BinaryKits/BinaryKits.Zpl/blob/2f08fe55dbf4afe25bcf011937a77b5f700511a1/src/BinaryKits.Zpl.Viewer/README.md

I think it already works very well of course there are still some points that need to be optimized but I think for the first throw the whole thing is already very good.

**Comment by YipingRuan** [comment]
Head still spinning and can't really feedback anything meaningful to you at the moment.

Out of curiosity, may I ask why the compression part is so critical?

**Comment by tinohager** [comment]
> Out of curiosity, may I ask why the compression part is so critical?

Nothing is critical I just collect the points where I still need to improve

**Comment by YipingRuan** [comment]
I can't build..
image

**Comment by YipingRuan** [comment]
To make the viewer work on Linux, seems we need to add the following to "BinaryKits.Zpl.Viewer.csproj"

````
    <PackageReference Include="SkiaSharp.NativeAssets.Linux" Version="2.80.3" />
    <PackageReference Include="SkiaSharp.NativeAssets.Linux.NoDependencies" Version="2.80.3" />
````

https://github.com/mono/SkiaSharp/issues/1341

**Comment by tinohager** [comment]
@YipingRuan Should we bring the current status back into the main branch? I think if more people want to collaborate it makes sense.

**Comment by YipingRuan** [comment]
Let's merge?

**Pull request merged**
