### PR TITLE
Add own viewer project

### PR DESCRIPTION
**Pull request by tinohager**
I have developed my own label render logic, which is currently only a prototype but actually works quite well.

### CODE REVIEW

**Comment by YipingRuan** [comment]
This is impressive. So `BinaryKits.Zpl.Viewer` generates the label without calling Labelary.

**Comment by tinohager** [comment]
> This is impressive. So `BinaryKits.Zpl.Viewer` generates the label without calling Labelary?

yes

**Comment by YipingRuan** [comment]
I can't even think how to handle the strange multi line behavior...

**Comment by tinohager** [comment]
My goal is not to build a perfect renderer but to generate a rough preview. The more accurate it becomes the better. There are some zpl files in the TestUi that I have tested with. You can try them with the WebApi. When you start it there is a small test application in the root.

**Comment by tinohager** [comment]
I would suggest to include the viewer in the main project. The basic functions are implemented. Now the finishing touches need to be made. Maybe you could optimize my web interface for testing. I have built it very minimalistic. The Labelary Client we could 
 publish from my point of view also as nuget package.

**Comment by YipingRuan** [comment]
Just alight few doubts

- include the viewer in the main project
Do you mean "Zpl.Label" project? How will it be linked/used?

- optimize my web interface for testing
Any suggested direction?

- The Labelary Client nuget
"BinaryKits.Zpl.Labelary" ?

**Comment by tinohager** [comment]
> Just alight few doubts
> 
> 
> 
> - include the viewer in the main project

No, the viewer has his own nuget package

> 
> Do you mean "Zpl.Label" project? How will it be linked/used?
> 
> 
> 
> - optimize my web interface for testing
> 
> Any suggested direction?

Maybe this project has his own  docker container to publish in the future. 

> 
> 
> 
> - The Labelary Client nuget
> 
> "BinaryKits.Zpl.Labelary" ?
> 
Yes
> 
> Btw, I believe permission is given so you no longer need to fork (if you prefer).

**Comment by YipingRuan** [comment]
"I would suggest to include the viewer in the main project."

Still confused about this part. Do you mean include viewer in the main solution? But that's already the case:
image

**Comment by tinohager** [comment]
yes in the solution 😄

**Comment by tinohager** [comment]
I just wanted to say that the viewer project is ready

**Comment by YipingRuan** [comment]
https://www.nuget.org/packages/BinaryKits.Zpl.Labelary/

NuGet is there, not enough description?

**Comment by tinohager** [comment]
@YipingRuan i'm not a great writer. but if you can think of something useful, feel free to expand it.

**Pull request merged**
