### PR TITLE
Add Labelary overlay to webapi

### PR DESCRIPTION
**Pull request by Int32Overflow**
This PR offers the possibility to superimpose the image of Labelary on the image of the viewer. This allows you to quickly see how accurate the new viewer is.

grafik

### CODE REVIEW

**Comment by primo-ppcg** [comment]
Seems useful to me. It makes it easy to see which areas need attention.

**Comment by tinohager** [comment]
I would suggest to do the two requests separately as it is a development support.

**Comment by Int32Overflow** [comment]
> I would suggest to do the two requests separately as it is a development support.

Which two requests do you mean?

**Comment by tinohager** [comment]
One for rendering with BinaryKits and a second for the optional request to Labelary. And the create the overlay in the browser

**Comment by Int32Overflow** [comment]
Okay then my pull requests fit right?

**Comment by tinohager** [comment]
You have built the overlay logic into the main request. Which is activated with the parameter `ShowLabelaryOverlay`. I don't think that's so great.

**Comment by Int32Overflow** [comment]
> You have built the overlay logic into the main request. Which is activated with the parameter `ShowLabelaryOverlay`. I don't think that's so great.

I do not understand the problem😔
Why is this not good?

**Comment by tinohager** [comment]
The Single Responsibility Principle (SRP)
The idea behind the SRP is that every class, module, or function in a program should have one responsibility/purpose in a program. As a commonly used definition, "every class should have only one reason to change". The class above violates the single responsibility principle

In your modified version, the function now has several tasks. If I want to add another service I have to change the existing code again. 

If you build an additional function you do not change the existing functions.

**Comment by YipingRuan** [comment]
@Int32Overflow 
I think he wants the new logic not to be inside the function `RenderZpl`, an easy adjust possible?

**Comment by primo-ppcg** [comment]
> One for rendering with BinaryKits and a second for the optional request to Labelary. And the create the overlay in the browser

I second this. It would also make it possible to turn the overlay on and off without the need fire off a new request.

**Comment by primo-ppcg** [comment]
Superseded by #156.

**Pull request closed without merging**
