### PR TITLE
fix: font scaling when only width is provided

### LINKED ISSUE #180: Text distortion
Thanks for the great work, I found the project today and started playing with it. I added support for cors (PR pending).
But once I started adding some real life exemple I found the text too distorted.
As far as I can tell zebra printers do not distort texts. any idea what might be causing this.
ex:
```
^XA
^FO8,8^A0,,32,^FD{name}^FS
^FO8,44^BC,80,,,,A^FD{barcode}^FS
^FO8,200^A0,,120,^FD{priceInclTax}^FS
^XZ
```
57, 43, 8
And compare with overlay/labelery.
image

### PR DESCRIPTION
**Pull request by yelhouti**
Fixes #180

### CODE REVIEW

**Review by primo-ppcg — APPROVED** [review]
Looks good to me. Resolves the linked issue, and all previous examples work properly.

**Comment by yelhouti** [comment]
@primo-ppcg do you have a CI configured to automatically compile the new docker image and push to the docker registry ?

**Comment by primo-ppcg** [comment]
> @primo-ppcg do you have a CI configured to automatically compile the new docker image and push to the docker registry ?

Yes, the online viewer will be automatically redeployed as soon as this PR is merged.

**Comment by YipingRuan** [comment]
> @primo-ppcg do you have a CI configured to automatically compile the new docker image and push to the docker registry ?

I guess it is working? https://github.com/BinaryKits/BinaryKits.Zpl/actions/runs/5776787312

**Comment by primo-ppcg** [comment]
The online viewer is already updated :+1:

**Comment by yelhouti** [comment]
@primo-ppcg thanks a lot for the reactivity

**Pull request merged**
